Add Apache ECharts HTTP Export Server
ecomfe/awesome-echarts pull request #48
Opened 2022-09-28 13:05 UTC by xiaomaiyun

Add Apache ECharts HTTP Export Server

Currently, there is no HTTP Export Server ( Server Side Rendering ) for ECharts. In view of this, we created [Apache ECharts HTTP Export Server](https://github.com/xiaomaigou/echarts-export-server). The export server is a Node.js-based service, which is easy to install and integrate on any system. It accepts either JSON-formatted chart options or SVGs, together with additional resources, and uses node canvas to render Apache ECharts charts to images (PNG, JPG, SVG , PDF and Base64) to be sent back to the user.The application can be used either as a CLI (Command Line Interface), as an HTTP server, or as a node.js module.. 

The repo is [here](https://github.com/xiaomaigou/echarts-export-server).

Thank you and look forward to contributing to this list.

2022-10-01 10:50 UTC, Ovilia requested changes

2022-10-01 10:50 UTC, Ovilia commented on README.md
> +- [Apache ECharts HTTP Export Server](https://github.com/xiaomaigou/echarts-export-server) @xiaomaiyun - This is a Node.js-based service, and uses node canvas to render Apache ECharts charts to image
`..` should be `.`. Please also remove the space after `SVG`.

2022-10-08 12:49 UTC, xiaomaiyun commented on README.md
> +- [Apache ECharts HTTP Export Server](https://github.com/xiaomaigou/echarts-export-server) @xiaomaiyun - This is a Node.js-based service, and uses node canvas to render Apache ECharts charts to image
It has been resolved, please review.

2022-10-09 06:40 UTC, Ovilia requested changes
Please put this under `Node.js` section.

2022-10-09 08:04 UTC, xiaomaiyun commented
> Please put this under `Node.js` section.

It has been resolved, please review.

2022-10-20 12:09 UTC, xiaomaiyun commented
> Please put this under `Node.js` section.

I change it.

please recheck.

2022-10-21 04:01 UTC, Ovilia requested changes
This list is in the alphabetic order, so please put it before the other two projects in this section.

2023-02-09 13:01 UTC, closed without merging