Update README.md
ecomfe/awesome-echarts pull request #54
Opened 2022-12-11 12:17 UTC by nico-robert

Added Tcl wrapper.

2023-01-12 02:28 UTC, Ovilia requested changes

2023-01-12 02:28 UTC, Ovilia commented on README.md
> +### Tcl
Please put this after Ruby section.

2023-01-12 06:59 UTC, nico-robert commented on README.md
> +### Tcl
Sorry @Ovilia , I don't understand `Tcl` section is after Ruby section I'm wrong ?
```
### Ruby

- [rails_charts](https://github.com/railsjazz/rails_charts) - create charts in Ruby on Rails application with just a few lines of code

### Tcl

- [ticklEcharts](https://github.com/nico-robert/ticklecharts) - Tcl wrapper for Apache ECharts
```

2023-01-16 06:55 UTC, Ovilia approved these changes

2023-01-16 06:55 UTC, Ovilia commented on README.md
> +### Tcl
Sorry. That should not be a problem for this PR. It seems `PHP` is in wrong order.

2023-01-16 06:57 UTC, merged